// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesteTecnico.Api.Domain.Accounts;
using TesteTecnico.Api.Domain.Transfers;
using TesteTecnico.Api.Infrastructure.Persistence;

#nullable disable

namespace TesteTecnico.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926161329_AddTransferCancelledAt")]
    partial class AddTransferCancelledAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "account_status", new[] { "active", "blocked", "inactive" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "bank_account_type", new[] { "checking", "savings" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pix_key_type", new[] { "cnpj", "cpf", "email", "phone", "random" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transfer_method", new[] { "bank_account", "pix" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transfer_status", new[] { "cancelled", "completed", "failed", "processing", "scheduled" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TesteTecnico.Api.Domain.AccountHolders.AccountHolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("account_holders", (string)null);
                });

            modelBuilder.Entity("TesteTecnico.Api.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("CheckDigit")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("OverdraftLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<AccountStatus>("Status")
                        .HasColumnType("account_status");

                    b.Property<BankAccountType>("Type")
                        .HasColumnType("bank_account_type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.HasIndex("BankId", "Branch", "Number")
                        .IsUnique();

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_balance_precision", "\"Balance\" = round(\"Balance\", 2)");

                            t.HasCheckConstraint("ck_accounts_balance_within_overdraft", "\"Balance\" >= -\"OverdraftLimit\"");

                            t.HasCheckConstraint("ck_accounts_overdraft_nonnegative", "\"OverdraftLimit\" >= 0");
                        });
                });

            modelBuilder.Entity("TesteTecnico.Api.Domain.Banks.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompeCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Ispb")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CompeCode")
                        .IsUnique();

                    b.HasIndex("Ispb")
                        .IsUnique();

                    b.ToTable("banks", (string)null);
                });

            modelBuilder.Entity("TesteTecnico.Api.Domain.Transfers.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TransferMethod>("Method")
                        .HasColumnType("transfer_method");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid");

                    b.Property<TransferStatus>("Status")
                        .HasColumnType("transfer_status");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("SourceAccountId", "CreatedAt");

                    b.HasIndex("Status", "ScheduledAt");

                    b.ToTable("transfers", null, t =>
                        {
                            t.HasCheckConstraint("ck_transfers_amount_precision", "\"Amount\" = round(\"Amount\", 2)");

                            t.HasCheckConstraint("ck_transfers_different_accounts", "\"SourceAccountId\" <> \"DestinationAccountId\"");

                            t.HasCheckConstraint("ck_transfers_positive_amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("TesteTecnico.Api.Domain.Accounts.Account", b =>
                {
                    b.HasOne("TesteTecnico.Api.Domain.Banks.Bank", null)
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesteTecnico.Api.Domain.AccountHolders.AccountHolder", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("TesteTecnico.Api.Domain.Accounts.PixKey", "PixKeys", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<PixKeyType>("Type")
                                .HasColumnType("pix_key_type");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("account_pix_keys", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("PixKeys");
                });

            modelBuilder.Entity("TesteTecnico.Api.Domain.Transfers.Transfer", b =>
                {
                    b.HasOne("TesteTecnico.Api.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TesteTecnico.Api.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
